### ISSUE TITLE
Sending in gems

### ISSUE THREAD

**Issue by dancinglightning** [planetruby/advent2017#1]
Hi Gerald,

nice idea with the calendar, thanks for doing it.

You say we can all send in our gems on the list, but you don't say how.

This is the issue, maybe a fix would be to have instructions in the mail or readme.

Off course i have one in mind and follow the process once you say.

Cheers

Torsten

**Comment by geraldb** [comment]
@dancinglightning You're more than welcome. The idea is to write-up an article in markdown, see the examples in the repo -> https://github.com/planetruby/advent2017   If you have an article in your repo or as a gist you can let me know and I can copy and paste the article with your permission into the /advent2017 repo in an upcoming day. Let me know if that makes sense.

**Comment by dancinglightning** [comment]
Ok. Possible. 
I would have thought that a branch at least, to coordinate. 
Even better, issues. So you do the write up, to get a common tone /style

⁣Sent from TypeApp ​

**Comment by geraldb** [comment]
@dancinglightning  What gems (or gem) are you interested in highlighting / writing-up?

**Comment by dancinglightning** [comment]
My all time favourite piece of work that hardly anybody knows about is https://github.com/jjyg/metasm

It compiles / decompiles about a dozen cpus and a handful of binary formats. In 100% ruby.

**Comment by geraldb** [comment]
@dancinglightning   Thanks for highlighting metasm. Looks great. Might be a little to the metal for this year's series. Big fan of compiler construction / binaries, etc. Will add metasm to  a new NOTES page. Cheers.

**Comment by dancinglightning** [comment]
@geraldb I think you should consider broadening the scope. Ruby suffers from the rails centric view people have of it, a self enforcing view. Especially if you like the metal, maybe others come and maybe we build a better vm one day (http://ruby-x.org/ :-)
I would even go as far as saying that by taking the lead like this you have claimed to broaden peoples mind. So if not you, who then.
I'll leave that with you, fine whichever way you go.

**Comment by geraldb** [comment]
@dancinglightning  FYI: Your metasm recommendation is published on the front page with your quote. Cheers.
